#!/usr/bin/env node

console.log('STARTING API SERVER....');
require('dotenv').config()
const http = require('http');
const app = require('./src/server');


/**
 * Get port from environment and store in Express.
 */

const port = process.env.PORT;
app.set('port', port);

/**
 * Create HTTP server.
 */
const server = http.createServer(app);

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
    const addr = server.address();
    console.log(`SERVER STARTED ON PORT ${addr}`);
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
    if (error.syscall !== 'listen') {
        throw error;
    }

    // handle specific listen errors with friendly messages
    switch (error.code) {
    case 'EACCES':
        console.error(`${port} requires elevated privileges`);
        process.exit(1);
        break;
    case 'EADDRINUSE':
        console.error(`${port} is already in use`);
        process.exit(1);
        break;
    default:
        throw error;
    }
}

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);
